name: CI

# Controls when the action will run. Workflow runs when main branch is updated.
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  bats:
    runs-on: ubuntu-latest
    name: Install Bats and bats libs
    strategy:
      matrix:
        bash: ["bash:3.2", "bash:4.4", "bash:5.0", "bash:5.1"]
    container:
      image: ${{ matrix.bash }}
    steps:
      - name: Install git
        run: apk add git

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Bats and bats libs
        uses: bats-core/bats-action@2.0.0
        with:
          support-path: ${{ github.workspace }}/test/libs/bats-support
          assert-path: ${{ github.workspace }}/test/libs/bats-assert
          file-path: ${{ github.workspace }}/test/libs/bats-file
          detik-install: false

      - name: Set ownership
        run: |
          # this is to fix GIT not liking owner of the checkout dir
          chown -R $(id -u):$(id -g) $PWD 
      
      - name: Checkout submodules
        run: git submodule update --init --recursive

      - name: Run main tests
        run: bats test/main.bats
