name: CI

# Controls when the action will run. Workflow runs when main branch is updated.
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  bats:
    runs-on: ubuntu-latest
    name: Install Bats and bats libs
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bats and bats libs
        uses: bats-core/bats-action@2.0.0
        with:
          support-path: ${{ github.workspace }}/test/libs/bats-support
          assert-path: ${{ github.workspace }}/test/libs/bats-assert
          file-path: ${{ github.workspace }}/test/libs/bats-file
          detik-install: false

      - name: Run main tests
        run: bats test/main.bats

      - name: Run prompts tests
        run: bats test/prompts.bats

      - name: Run validators tests
        run: bats test/validators.bats
